/* Static content dictionaries: chart explanations (INFO), data provenance
 * (PROV) and code->label maps (C). Pure data, no logic, no DOM. */

export const INFO = {
  stateConsumption: { title: 'Food spending by state', what: 'This chart shows how much money households in each state spend on food in one month. Blue bars are villages. Green bars are cities. The numbers are survey estimates for all of India.', look: 'Compare the bar heights. Taller bars mean more food spending in that state.', source: 'Level 5 food consumption records, with survey weights.' },
  sectorShare: { title: 'Villages vs cities', what: 'This circle splits all food spending into two parts, villages and cities. The larger part shows where most food is bought.', look: 'Villages spend more because most Indians live there.', source: 'Level 5 food consumption records, with survey weights.' },
  ooh: { title: 'Home vs eating out', what: 'This circle splits food spending into meals at home and meals outside the home. Outside meals include food from shops and street stalls.', look: 'Almost all food is eaten at home.', source: 'Level 5 food consumption records.' },
  ageGroup: { title: 'Population by age group', what: 'These bars show how many people are in each age group. Blue is men and red is women. The bars show the age structure of India.', look: 'A wide middle means many working-age people.', source: 'Level 3 individual records, with survey weights.' },
  gender: { title: 'Men and women', what: 'This circle shows the number of men and women in India, from the survey.', look: 'India has more men than women.', source: 'Level 3 individual records, with survey weights.' },
  pyramid: { title: 'Population pyramid', what: 'This pyramid shows age on the vertical axis. Men go to one side and women go to the other side. It shows age and gender at the same time.', look: 'A wide base means a young population.', source: 'Level 3 individual records.' },
  composition: { title: 'Men and women by age', what: 'Each bar shows the share of men and women inside one age group. The two parts add to 100 percent.', look: 'The share of women can rise in older age groups.', source: 'Level 3 individual records.' },
  education: { title: 'Education levels by state', what: 'These stacked bars show the highest education level of people in each state. Each color is one education level.', look: 'More color above means a more educated state.', source: 'Level 3 individual records.' },
  marital: { title: 'Marital status (adults)', what: 'These bars show the marital status of adults aged 15 and above. Married people form the largest group.', look: 'Most adults are married. Widows are more common among women.', source: 'Level 3 individual records, adults only.' },
  internet: { title: 'Internet use by age', what: 'These bars show who used the internet in the last 30 days. Blue is users and red is non-users, for each age group.', look: 'Internet use is higher among young people and in cities.', source: 'Level 3 individual records.' },
  meals: { title: 'Meals per day', what: 'These bars show how many meals people usually take each day. Almost everyone in India takes three meals.', look: 'Look for very small bars. They show people who skip meals.', source: 'Level 3 individual records.' },
  relation: { title: 'Family members', what: 'This chart shows the place of each person in the household, such as head, spouse, or child. Most members are children of the head.', look: 'One head per household. Children form the largest group.', source: 'Level 3 individual records.' },
  hhsize: { title: 'House size', what: 'These bars show how many people live in each household. Most Indian households have four to five members.', look: 'The tallest bar is the most common family size.', source: 'Level 3 household records.' },
  hhtype: { title: 'Main income source', what: 'This chart groups households by their main source of income. The groups include self-employment, wage work, and casual labour.', look: 'See which income type is most common in each area.', source: 'Level 3 household records.' },
  socialgroup: { title: 'Social group', what: 'These bars show the social group of the household head. The groups are Scheduled Tribe, Scheduled Caste, Other Backward Class, and others.', look: 'OBC is the largest group in India.', source: 'Level 3 household records.' },
  religion: { title: 'Religion of household head', what: 'These bars show the religion of the head of each household.', look: 'Compare the size of each bar.', source: 'Level 3 household records.' },
  dwelling: { title: 'House type', what: 'This circle shows the type of house people live in. Pucca houses use strong materials. Katcha houses use mud and thatch.', look: 'The largest slice is the most common house type.', source: 'Level 3 household records.' },
  energy: { title: 'Cooking fuel', what: 'This circle shows the fuel that households use for cooking. LPG and firewood are the most common fuels in India.', look: 'LPG use is higher in cities. Firewood is higher in villages.', source: 'Level 3 household records.' },
  lighting: { title: 'Lighting source', what: 'This circle shows the main source of light in the home. Electricity serves almost every household in India.', look: 'Very few homes still use kerosene.', source: 'Level 3 household records.' },
  land: { title: 'Land ownership', what: 'This circle shows whether households own land. Land ownership matters for income from farming.', look: 'Most rural households own some land.', source: 'Level 3 household records.' },
  ration: { title: 'Ration cards', what: 'This circle shows the ration cards that households hold. A ration card gives subsidized food from fair price shops.', look: 'Most households hold some type of ration card.', source: 'Level 3 household records.' },
  ujjwala: { title: 'Free LPG connection (Ujjwala)', what: 'This circle shows households that got a free LPG connection under the Ujjwala scheme. The scheme helps poor households cook with gas.', look: 'Compare the yes and no parts.', source: 'Level 3 household records.' },
  foodItems: { title: 'Top 20 food items by spending', what: 'These bars rank the food items that Indian households buy the most. Each bar is the monthly spending on one item.', look: 'The longest bars are the biggest food items, such as milk, vegetables, and cereals.', source: 'Level 5 food consumption records.' },
  consumpDist: { title: 'Food spending by state', what: 'One bar for each state. Each bar is the total monthly food spending of that state.', look: 'Large states show the biggest totals.', source: 'Level 5 food consumption records.' },
  perHH: { title: 'Average spend per item', what: 'This chart shows the average money that a household spends on one food item in one month. Blue is village households and green is city households.', look: 'Compare the village and city averages.', source: 'Level 5 food consumption records.' },
  foodSource: { title: 'Where food comes from', what: 'These bars show where households get their food. Purchase is the main source. Home production and free collection are the other sources.', look: 'Purchase is the main source in both areas.', source: 'Level 5 food consumption records.' },
  onlineGrocery: { title: 'Online grocery shopping', what: 'This circle shows households that bought groceries online in the last 30 days.', look: 'Online grocery is still a small share of all food buying.', source: 'Level 4 household records.' },
  pds: { title: 'Ration from fair price shops', what: 'This circle shows households that received ration from a fair price shop in the last 30 days. The ration includes rice, wheat, and sugar.', look: 'Most households received some ration.', source: 'Level 4 household records.' },
  lpg: { title: 'LPG cylinder subsidy', what: 'This circle shows households that received a subsidy on LPG cylinders.', look: 'Compare the yes and no parts.', source: 'Level 7 household records.' },
  electricity: { title: 'Free electricity', what: 'This circle shows households that get free electricity. The benefit reduces the power bill.', look: 'Free electricity helps poor households.', source: 'Level 7 household records.' },
  ayushman: { title: 'Ayushman health card', what: 'This circle shows households with an Ayushman Bharat health card. The card gives free treatment in listed hospitals.', look: 'Compare the yes and no parts.', source: 'Level 7 household records.' },
  school: { title: 'Children in school', what: 'This circle shows households with a child in school. The school can be government or private.', look: 'Compare villages and cities.', source: 'Level 7 household records.' },
  schoolSplit: { title: 'Government vs private schools', what: 'These bars show the number of children in government schools and private schools. Blue is government and green is private.', look: 'Government schools serve more village children. Private schools serve more city children.', source: 'Level 7 household records.' },
};

export const PROV = {
  stateConsumption: { file: 'food_consumption.parquet', cols: ['State', 'Sector', 'Total_Consumption_Value', 'Multiplier'], agg: 'state_consumption.json' },
  sectorShare: { file: 'food_consumption.parquet', cols: ['Sector', 'Total_Consumption_Value', 'Multiplier'], agg: 'state_consumption.json' },
  ooh: { file: 'food_consumption.parquet', cols: ['OutOfHome_Consumption_Value', 'Total_Consumption_Value', 'Multiplier'], agg: 'state_consumption.json' },
  ageGroup: { file: 'individual_characteristics.parquet', cols: ['Age', 'Gender', 'Multiplier'], agg: 'demographics.json' },
  gender: { file: 'individual_characteristics.parquet', cols: ['Gender', 'Multiplier'], agg: 'demographics.json' },
  pyramid: { file: 'individual_characteristics.parquet', cols: ['Age', 'Gender', 'Multiplier'], agg: 'demographics.json' },
  composition: { file: 'individual_characteristics.parquet', cols: ['Age', 'Gender', 'Multiplier'], agg: 'demographics.json' },
  education: { file: 'individual_characteristics.parquet', cols: ['Education_Level', 'State', 'Multiplier'], agg: 'education.json' },
  marital: { file: 'individual_characteristics.parquet', cols: ['Marital_Status', 'Age', 'Gender', 'Multiplier'], agg: 'people.json' },
  internet: { file: 'individual_characteristics.parquet', cols: ['Used_Internet_Last_30_Days', 'Age', 'Sector', 'Multiplier'], agg: 'people.json' },
  meals: { file: 'individual_characteristics.parquet', cols: ['Meals_Usually_Taken_Per_Day', 'Sector', 'Multiplier'], agg: 'people.json' },
  relation: { file: 'individual_characteristics.parquet', cols: ['Relation_to_Head', 'Sector', 'Multiplier'], agg: 'people.json' },
  hhsize: { file: 'household_economic.parquet', cols: ['HH_Size_FDQ', 'Sector', 'Multiplier'], agg: 'household_extras.json' },
  hhtype: { file: 'household_economic.parquet', cols: ['Household_Type', 'Multiplier'], agg: 'household_characteristics.json' },
  socialgroup: { file: 'household_economic.parquet', cols: ['Social_Group_of_HH_Head', 'Sector', 'Multiplier'], agg: 'household_extras.json' },
  religion: { file: 'household_economic.parquet', cols: ['Religion_of_HH_Head', 'Multiplier'], agg: 'household_characteristics.json' },
  dwelling: { file: 'household_economic.parquet', cols: ['Type_of_Dwelling_Unit', 'Multiplier'], agg: 'household_characteristics.json' },
  energy: { file: 'household_economic.parquet', cols: ['Energy_Source_Cooking', 'Multiplier'], agg: 'household_characteristics.json' },
  lighting: { file: 'household_economic.parquet', cols: ['Energy_Source_Lighting', 'Sector', 'Multiplier'], agg: 'household_extras.json' },
  land: { file: 'household_economic.parquet', cols: ['Land_Ownership', 'Multiplier'], agg: 'household_characteristics.json' },
  ration: { file: 'household_economic.parquet', cols: ['Ration_Card_Type', 'Multiplier'], agg: 'household_characteristics.json' },
  ujjwala: { file: 'household_economic.parquet', cols: ['Benefitted_From_PMGKY', 'Sector', 'Multiplier'], agg: 'household_extras.json' },
  foodItems: { file: 'food_consumption.parquet', cols: ['Item_Code', 'Total_Consumption_Value', 'Multiplier'], agg: 'food_rankings.json' },
  consumpDist: { file: 'food_consumption.parquet', cols: ['State', 'Total_Consumption_Value', 'Multiplier'], agg: 'state_consumption.json' },
  perHH: { file: 'food_consumption.parquet', cols: ['State', 'Sector', 'Total_Consumption_Value', 'Multiplier'], agg: 'state_consumption.json' },
  foodSource: { file: 'food_consumption.parquet', cols: ['Source', 'Sector'], agg: 'spending_extras.json' },
  onlineGrocery: { file: 'consumption_4_1.parquet', cols: ['Online_Groceries', 'Sector', 'Multiplier'], agg: 'spending_extras.json' },
  pds: { file: 'consumption_4_1.parquet', cols: ['Ration_Any_Item_Last_30_Days', 'Sector', 'Multiplier'], agg: 'schemes.json' },
  lpg: { file: 'consumption_4_2.parquet', cols: ['LPG_subsidy_received', 'Sector', 'Multiplier'], agg: 'schemes.json' },
  electricity: { file: 'consumption_4_2.parquet', cols: ['Free_electricity', 'Sector', 'Multiplier'], agg: 'schemes.json' },
  ayushman: { file: 'consumption_4_2.parquet', cols: ['Ayushman_beneficiary', 'Sector', 'Multiplier'], agg: 'schemes.json' },
  school: { file: 'consumption_4_2.parquet', cols: ['Any_member_attended_school', 'Sector', 'Multiplier'], agg: 'schemes.json' },
  schoolSplit: { file: 'consumption_4_2.parquet', cols: ['Num_govt_school_attended', 'Num_private_school_attended', 'Multiplier'], agg: 'schemes.json' },
};

export const C = {
  marital: { 1: 'Never married', 2: 'Married', 3: 'Widowed', 4: 'Divorced or separated' },
  relation: { 1: 'Head', 2: 'Spouse', 3: 'Married child', 4: 'Child\'s spouse', 5: 'Unmarried child', 6: 'Grandchild', 7: 'Parent', 8: 'Sibling', 9: 'Other relative' },
  social: { 1: 'Scheduled Tribe', 2: 'Scheduled Caste', 3: 'OBC', 9: 'Others' },
  lighting: { 1: 'Electricity', 2: 'Kerosene', 3: 'Solar', 5: 'Gas', 6: 'Candle', 9: 'No lighting' },
  cooking: { '01': 'Firewood', '02': 'LPG / gas', '03': 'Other biofuel', '04': 'Dung cake', '05': 'Coal', '06': 'Kerosene', '09': 'Biogas', '11': 'No cooking', '12': 'Other' },
  dwelling: { 1: 'Pucca', 2: 'Semi-pucca', 3: 'Katcha' },
  land: { 1: 'Owns land', 2: 'No land' },
  religion: { 1: 'Hindu', 2: 'Muslim', 3: 'Christian', 4: 'Sikh', 5: 'Buddhist', 6: 'Jain', 9: 'Others', 0: 'Not reported' },
  hhtype: { 1: 'Self-employed, non-farm', 2: 'Self-employed, farm', 3: 'Casual labour, farm', 4: 'Casual labour, non-farm', 5: 'Regular wage or salary', 6: 'Others', 9: 'Other' },
  ration: { 0: 'No ration card', 1: 'Card type 1', 2: 'Card type 2', 3: 'Card type 3', 4: 'Card type 4', 5: 'Card type 5', 9: 'Not reported' },
  foodsrc: { 1: 'Purchased', 2: 'Home-produced', 3: 'Exchanged', 4: 'Gift', 5: 'Free collection', 6: 'From employer', 7: 'From others', 9: 'Other' },
};
