/* Static content dictionaries: chart explanations (INFO), data provenance
 * (PROV) and code->label maps (C). Pure data, no logic, no DOM. */

export const INFO = {
  stateConsumption: { title: 'Food spending by state', what: 'This chart shows how much money households in each state spend on food in one month. Blue bars are villages. Green bars are cities. The numbers are survey estimates for all of India.', look: 'Compare the bar heights. Taller bars mean more food spending in that state.', source: 'Level 5 food consumption records, with survey weights.' },
  sectorShare: { title: 'Villages vs cities', what: 'This circle splits all food spending into two parts, villages and cities. The larger part shows where most food is bought.', look: 'Villages spend more because most Indians live there.', source: 'Level 5 food consumption records, with survey weights.' },
  ooh: { title: 'Home vs eating out', what: 'This circle splits food spending into meals at home and meals outside the home. Outside meals include food from shops and street stalls.', look: 'Almost all food is eaten at home.', source: 'Level 5 food consumption records.' },
  ageGroup: { title: 'Population by age group', what: 'These bars show how many people are in each age group. Blue is men and red is women. The bars show the age structure of India.', look: 'A wide middle means many working-age people.', source: 'Level 3 individual records, with survey weights.' },
  gender: { title: 'Men and women', what: 'This circle shows the number of men and women in India, from the survey.', look: 'India has more men than women.', source: 'Level 3 individual records, with survey weights.' },
  pyramid: { title: 'Population pyramid', what: 'This pyramid shows age on the vertical axis. Men go to one side and women go to the other side. It shows age and gender at the same time.', look: 'A wide base means a young population.', source: 'Level 3 individual records.' },
  education: { title: 'Education levels by state', what: 'These stacked bars show the highest education level of people in each state. Each color is one education level.', look: 'More color above means a more educated state.', source: 'Level 3 individual records.' },
  marital: { title: 'Marital status (adults)', what: 'These bars show the marital status of adults aged 15 and above. Married people form the largest group.', look: 'Most adults are married. Widows are more common among women.', source: 'Level 3 individual records, adults only.' },
  internet: { title: 'Internet use by age', what: 'These bars show who used the internet in the last 30 days. Blue is users and red is non-users, for each age group.', look: 'Internet use is higher among young people and in cities.', source: 'Level 3 individual records.' },
  relation: { title: 'Family members', what: 'This chart shows the place of each person in the household, such as head, spouse, or child. Most members are children of the head.', look: 'One head per household. Children form the largest group.', source: 'Level 3 individual records.' },
  hhsize: { title: 'House size', what: 'These bars show how many people live in each household. Most Indian households have four to five members.', look: 'The tallest bar is the most common family size.', source: 'Level 3 household records.' },
  hhtype: { title: 'Main income source', what: 'This chart groups households by their main source of income. The groups include self-employment, wage work, and casual labour.', look: 'See which income type is most common in each area.', source: 'Level 3 household records.' },
  socialgroup: { title: 'Social group', what: 'These bars show the social group of the household head. The groups are Scheduled Tribe, Scheduled Caste, Other Backward Class, and others.', look: 'OBC is the largest group in India.', source: 'Level 3 household records.' },
  religion: { title: 'Religion of household head', what: 'These bars show the religion of the head of each household.', look: 'Compare the size of each bar.', source: 'Level 3 household records.' },
  dwelling: { title: 'House type', what: 'This circle shows the type of house people live in. Pucca houses use strong materials. Katcha houses use mud and thatch.', look: 'The largest slice is the most common house type.', source: 'Level 3 household records.' },
  energy: { title: 'Cooking fuel', what: 'This circle shows the fuel that households use for cooking. LPG and firewood are the most common fuels in India.', look: 'LPG use is higher in cities. Firewood is higher in villages.', source: 'Level 3 household records.' },
  lighting: { title: 'Lighting source', what: 'This circle shows the main source of light in the home. Electricity serves almost every household in India.', look: 'Very few homes still use kerosene.', source: 'Level 3 household records.' },
  land: { title: 'Land ownership', what: 'This circle shows whether households own land. Land ownership matters for income from farming.', look: 'Most rural households own some land.', source: 'Level 3 household records.' },
  ration: { title: 'Ration cards', what: 'This circle shows the ration cards that households hold. A ration card gives subsidized food from fair price shops.', look: 'Most households hold some type of ration card.', source: 'Level 3 household records.' },
  ujjwala: { title: 'Free LPG connection (Ujjwala)', what: 'This circle shows households that got a free LPG connection under the Ujjwala scheme. The scheme helps poor households cook with gas.', look: 'Compare the yes and no parts.', source: 'Level 3 household records.' },
  foodItems: { title: 'Top 20 food items by spending', what: 'These bars rank the food items that Indian households buy the most. Each bar is the monthly spending on one item.', look: 'The longest bars are the biggest food items, such as milk, vegetables, and cereals.', source: 'Level 5 food consumption records.' },
  perHH: { title: 'Average spend per item', what: 'This chart shows the average money that a household spends on one food item in one month. Blue is village households and green is city households.', look: 'Compare the village and city averages.', source: 'Level 5 food consumption records.' },
  foodSource: { title: 'Where food comes from', what: 'These bars show where households get their food. Purchase is the main source. Home production and free collection are the other sources.', look: 'Purchase is the main source in both areas.', source: 'Level 5 food consumption records.' },
  pds: { title: 'Ration from fair price shops', what: 'This circle shows households that received ration from a fair price shop in the last 30 days. The ration includes rice, wheat, and sugar.', look: 'Most households received some ration.', source: 'Level 4 household records.' },
  lpg: { title: 'LPG cylinder subsidy', what: 'This circle shows households that received a subsidy on LPG cylinders.', look: 'Compare the yes and no parts.', source: 'Level 7 household records.' },
  electricity: { title: 'Free electricity', what: 'This circle shows households that get free electricity. The benefit reduces the power bill.', look: 'Free electricity helps poor households.', source: 'Level 7 household records.' },
  ayushman: { title: 'Ayushman health card', what: 'This circle shows households with an Ayushman Bharat health card. The card gives free treatment in listed hospitals.', look: 'Compare the yes and no parts.', source: 'Level 7 household records.' },
  school: { title: 'Children in school', what: 'This circle shows households with a child in school. The school can be government or private.', look: 'Compare villages and cities.', source: 'Level 7 household records.' },
  schoolSplit: { title: 'Government vs private schools', what: 'These bars show the number of children in government schools and private schools. Blue is government and green is private.', look: 'Government schools serve more village children. Private schools serve more city children.', source: 'Level 7 household records.' },
  schoolBenefits: { title: 'Free school items', what: 'These bars show households whose children got free textbooks, stationery, school bags, or a fee waiver from the school.', look: 'Free textbooks reach the most households. A fee waiver reaches fewer.', source: 'Level 7 household records.' },
  schoolMeals: { title: 'School meals (mid-day)', what: 'This circle shows school-age children who got a meal from school, such as the mid-day meal scheme.', look: 'Most school children receive a school meal.', source: 'Level 3 individual records, ages 5 to 17.' },
  ayushmanDetail: { title: 'Ayushman health card and care', what: 'These bars show households with an Ayushman card, a hospital case in the last year, and those who got a medical benefit.', look: 'More households hold the card than received a medical benefit.', source: 'Level 7 household records.' },
  mpceDist: { title: 'Spending per person: poor to rich', what: 'This chart ranks people from the bottom to the top of the spending scale. Each bar shows the monthly spending per person at that step (10th to 90th percentile). The last bar is the national average. Each person counts once, through the household they live in.', look: 'People near the top spend many times more than people near the bottom.', source: 'Level 6 monthly consumption records (visit 1).' },
  mpceCurve: { title: 'Spending per person by group', what: 'Each line is one group of people. It runs from the bottom of the spending scale to the top (1st to 99th percentile). At each step the line shows the monthly spending per person. Each person counts once, through the household they live in. Pick a comparison: rural or urban, state, household type, social group, religion, land, cooking fuel, ration card, house type, or survey month. We show a group only when its raw sample is large enough: 2,000+ sampled households for household filters, 300+ for survey month. The state view keeps the 12 states/UTs with the highest median spending.', look: 'A line that sits higher is a group that spends more. Lines that cross show where one group overtakes another.', source: 'Monthly consumption records (visit 1), split by household filters.' },
  mpceState: { title: 'Spending per person by state', what: 'These bars show the monthly spending per person in each state. Blue is villages and green is cities.', look: 'The gap between the top and bottom states is large.', source: 'Level 6 monthly consumption records (visit 1).' },
  budgetSplit: { title: 'Food vs everything else', what: 'This circle splits the total monthly budget into food and everything else, such as clothes, rent, and medical care.', look: 'Food takes about half of the budget.', source: 'Level 5 food records vs level 6 total records.' },
  clothing: { title: 'Clothing and footwear spending', what: 'These bars show the monthly spending on clothing, bedding, and footwear, converted from the yearly survey record. The numbers cover all of India.', look: 'Clothing is the largest of the three.', source: 'Level 13 non-food consumption records (365-day recall, shown per month).' },
  services: { title: 'Spending on services', what: 'These bars show the monthly spending on services: education, medical care, transport, rent, and other services. Education and hospital records are yearly, converted to per month.', look: 'Education and medical care are the largest service costs.', source: 'Level 9-11 consumption records (mixed recall, shown per month).' },
  fuel: { title: 'Fuel and energy spending', what: 'These bars show the monthly money spent on fuel and energy, such as electricity, LPG, and firewood.', look: 'Electricity and LPG are the largest fuel costs.', source: 'Level 8 fuel consumption records (30-day recall).' },
  tobacco: { title: 'Tobacco and intoxicants', what: 'These bars show the monthly spending on tobacco products and intoxicants such as liquor, converted from the 7-day survey record.', look: 'Tobacco spending is larger than intoxicants.', source: 'Level 12 consumption records (7-day recall, shown per month).' },
  durables: { title: 'Durables bought last year', what: 'These bars show how many households bought each durable item, such as a fan, mobile, or TV, in the last year.', look: 'Fans and mobiles are bought by the most households.', source: 'Level 14 durable purchase records.' },
  onlineChannels: { title: 'Online purchases by category', what: 'These bars show households that bought goods online, by category such as medicine, services, and education.', look: 'Compare the categories.', source: 'Level 7 household online purchase records.' },
  literacy: { title: 'Literacy rate', what: 'These bars show the share of people who can read and write. A person with at least one year of education counts as literate.', look: 'Men have a higher literacy rate than women.', source: 'Level 3 individual records.' },
  employment: { title: 'Who is working', what: 'These bars show households engaged in an economic activity, such as farming or wage work.', look: 'Most households have at least one working member.', source: 'Level 3 household records.' },
};

export const PROV = {
  stateConsumption: { file: 'food_consumption.parquet', cols: ['State', 'Sector', 'Total_Consumption_Value', 'Multiplier'], agg: 'state_consumption.json' },
  sectorShare: { file: 'food_consumption.parquet', cols: ['Sector', 'Total_Consumption_Value', 'Multiplier'], agg: 'state_consumption.json' },
  ooh: { file: 'food_consumption.parquet', cols: ['OutOfHome_Consumption_Value', 'Total_Consumption_Value', 'Multiplier'], agg: 'state_consumption.json' },
  ageGroup: { file: 'individual_characteristics.parquet', cols: ['Age', 'Gender', 'Multiplier'], agg: 'demographics.json' },
  gender: { file: 'individual_characteristics.parquet', cols: ['Gender', 'Multiplier'], agg: 'demographics.json' },
  pyramid: { file: 'individual_characteristics.parquet', cols: ['Age', 'Gender', 'Multiplier'], agg: 'demographics.json' },
  education: { file: 'individual_characteristics.parquet', cols: ['Education_Level', 'State', 'Multiplier'], agg: 'education.json' },
  marital: { file: 'individual_characteristics.parquet', cols: ['Marital_Status', 'Age', 'Gender', 'Multiplier'], agg: 'people.json' },
  internet: { file: 'individual_characteristics.parquet', cols: ['Used_Internet_Last_30_Days', 'Age', 'Sector', 'Multiplier'], agg: 'people.json' },
  relation: { file: 'individual_characteristics.parquet', cols: ['Relation_to_Head', 'Sector', 'Multiplier'], agg: 'people.json' },
  hhsize: { file: 'household_economic.parquet', cols: ['HH_Size_FDQ', 'Sector', 'Multiplier'], agg: 'household_extras.json' },
  hhtype: { file: 'household_economic.parquet', cols: ['Household_Type', 'Multiplier'], agg: 'household_characteristics.json' },
  socialgroup: { file: 'household_economic.parquet', cols: ['Social_Group_of_HH_Head', 'Sector', 'Multiplier'], agg: 'household_extras.json' },
  religion: { file: 'household_economic.parquet', cols: ['Religion_of_HH_Head', 'Multiplier'], agg: 'household_characteristics.json' },
  dwelling: { file: 'household_economic.parquet', cols: ['Type_of_Dwelling_Unit', 'Multiplier'], agg: 'household_characteristics.json' },
  energy: { file: 'household_economic.parquet', cols: ['Energy_Source_Cooking', 'Multiplier'], agg: 'household_characteristics.json' },
  lighting: { file: 'household_economic.parquet', cols: ['Energy_Source_Lighting', 'Sector', 'Multiplier'], agg: 'household_extras.json' },
  land: { file: 'household_economic.parquet', cols: ['Land_Ownership', 'Multiplier'], agg: 'household_characteristics.json' },
  ration: { file: 'household_economic.parquet', cols: ['Ration_Card_Type', 'Multiplier'], agg: 'household_characteristics.json' },
  ujjwala: { file: 'household_economic.parquet', cols: ['Benefitted_From_PMGKY', 'Sector', 'Multiplier'], agg: 'household_extras.json' },
  foodItems: { file: 'food_consumption.parquet', cols: ['Item_Code', 'Total_Consumption_Value', 'Multiplier'], agg: 'food_rankings.json' },
  perHH: { file: 'food_consumption.parquet', cols: ['State', 'Sector', 'Total_Consumption_Value', 'Multiplier'], agg: 'state_consumption.json' },
  foodSource: { file: 'food_consumption.parquet', cols: ['Source', 'Sector'], agg: 'spending_extras.json' },
  pds: { file: 'consumption_4_1.parquet', cols: ['Ration_Any_Item_Last_30_Days', 'Sector', 'Multiplier'], agg: 'schemes.json' },
  lpg: { file: 'consumption_4_2.parquet', cols: ['LPG_subsidy_received', 'Sector', 'Multiplier'], agg: 'schemes.json' },
  electricity: { file: 'consumption_4_2.parquet', cols: ['Free_electricity', 'Sector', 'Multiplier'], agg: 'schemes.json' },
  ayushman: { file: 'consumption_4_2.parquet', cols: ['Ayushman_beneficiary', 'Sector', 'Multiplier'], agg: 'schemes.json' },
  school: { file: 'consumption_4_2.parquet', cols: ['Any_member_attended_school', 'Sector', 'Multiplier'], agg: 'schemes.json' },
  schoolSplit: { file: 'consumption_4_2.parquet', cols: ['Num_govt_school_attended', 'Num_private_school_attended', 'Multiplier'], agg: 'schemes.json' },
  schoolBenefits: { file: 'consumption_4_2.parquet', cols: ['Free_textbooks_received', 'Free_stationery_received', 'Free_school_bag_received', 'Fee_waiver_received', 'Multiplier'], agg: 'schemes.json' },
  schoolMeals: { file: 'individual_characteristics.parquet', cols: ['Meals_From_School', 'Age', 'Multiplier'], agg: 'schemes.json' },
  ayushmanDetail: { file: 'consumption_4_2.parquet', cols: ['Ayushman_beneficiary', 'Hospitalization_case', 'Medical_benefit_received', 'Multiplier'], agg: 'schemes.json' },
  mpceDist: { file: 'supplementary_consumption.parquet', cols: ['MONTHLY_CONSUMPTION_EXP', 'HOUSEHOLD_SIZE'], agg: 'income.json' },
  mpceCurve: { file: 'supplementary_consumption.parquet + household_economic.parquet', cols: ['MONTHLY_CONSUMPTION_EXP', 'HOUSEHOLD_SIZE', 'Household_Type', 'Social_Group_of_HH_Head', 'Religion_of_HH_Head', 'Land_Ownership', 'Energy_Source_Cooking', 'Ration_Card_Type', 'Type_of_Dwelling_Unit', 'VISIT_MONTH'], agg: 'income.json (curves · p1–p99, weighted by Multiplier × household size)' },
  mpceState: { file: 'supplementary_consumption.parquet', cols: ['State', 'MONTHLY_CONSUMPTION_EXP', 'HOUSEHOLD_SIZE'], agg: 'income.json' },
  budgetSplit: { file: 'food_consumption + supplementary_consumption', cols: ['Total_Consumption_Value', 'MONTHLY_CONSUMPTION_EXP'], agg: 'income.json' },
  clothing: { file: 'consumption_13.parquet', cols: ['ITEM_CODE', 'VALUE', 'Multiplier'], agg: 'spending_extras.json' },
  services: { file: 'consumption_9_10_11.parquet', cols: ['Item_Code_9_1_to_11_4', 'Value_Rs_9_1_to_11_4', 'Multiplier'], agg: 'spending_extras.json' },
  fuel: { file: 'consumption_8_1.parquet', cols: ['Item_Code_8_1', 'Total_consumption_value_rs', 'Multiplier'], agg: 'spending_extras.json' },
  tobacco: { file: 'consumption_12.parquet', cols: ['Item_Code_12_series', 'Total_Consumption_Value_12_serie', 'Multiplier'], agg: 'spending_extras.json' },
  durables: { file: 'consumption_14.parquet', cols: ['ITEM_CODE', 'FIRST_PURCHASE_NUMBER', 'Multiplier'], agg: 'spending_extras.json' },
  onlineChannels: { file: 'consumption_4_2.parquet', cols: ['Online_purchase_medicine', 'Online_purchase_services', 'Online_purchase_education', 'Online_purchase_fuel_light', 'Online_purchase_toilet_articles'], agg: 'spending_extras.json' },
  literacy: { file: 'individual_characteristics.parquet', cols: ['Years_of_Education', 'Gender', 'Sector', 'Multiplier'], agg: 'people.json' },
  employment: { file: 'household_economic.parquet', cols: ['Engaged_in_Economic_Activity_Las', 'Sector', 'Multiplier'], agg: 'household_extras.json' },
};

// Chart code->label maps, generated from the official questionnaire by
// build_parquet_code_map.py (single source of truth: hces-code/parquet-code-map.json).
export { C } from './code-maps.generated.js';
